language: objective-c
osx_image: xcode7.2b1
xcode_workspace: Strutter.xcworkspace
env:
  global:
    - IOS_SCHEME="Strutter iOS"
    - IOS_OA_SCHEME="Strutter iOS OALayout"
    - OSX_SCHEME = "Strutter Mac"
    - IOS_SDK="iphonesimulator"
    - OSX_SDK="macosx10.11"
    - IOS8_32="DESTINATION=\"OS=8.4,name=iPhone 4s\""
    - IOS8_64="DESTINATION=\"OS=8.4,name=iPhone 5s\""
    - IOS9_32="DESTINATION=\"OS=9.1,name=iPhone 4s\""
    - IOS9_64="DESTINATION=\"OS=9.1,name=iPhone 5s\""
    - OSX_64="arch=x86_64"
  matrix:
    - DESTINATION="$IOS8_32" SCHEME="$IOS_OA_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="$IOS8_64" SCHEME="$IOS_OA_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="$IOS9_32" SCHEME="$IOS_OA_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="$IOS9_64" SCHEME="$IOS_OA_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="$IOS9_32" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="$IOS9_64" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="$OSX_64" SCHEME="$OSX_SCHEME" SDK="$OSX_SDK"
# xcode_sdk: 
  # - iphonesimulator
  # - macosx10.11
# matrix:
#   exclude:
#     -
#       xcode_scheme: Strutter iOS
#       xcode_sdk: macosx10.11
#     -
#       xcode_scheme: Strutter iOS OALayout
#       xcode_sdk: macosx10.11
#     - 
#       xcode_scheme: Strutter Mac
#       xcode_sdk: iphonesimulator9.0
#     - 
#       xcode_scheme: Strutter iOS
#       env: "DESTINATION=\"OS=8.4,name=iPhone 5s\""
#     - 
#       xcode_scheme: Strutter iOS
#       env: "DESTINATION=\"OS=8.4,name=iPhone 4s\""
#   include:
#     -
#       xcode_scheme: Strutter Mac
#       env: DESTINATION="arch=x86_64"
script: 
  - xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
