language: objective-c
osx_image: xcode7.2b1
xcode_workspace: Strutter.xcworkspace
env:
  matrix:
    - "DESTINATION=\"OS=8.4,name=iPhone 4s\""
    - "DESTINATION=\"OS=9.1,name=iPhone 4s\""
    - "DESTINATION=\"OS=8.4,name=iPhone 5s\""
    - "DESTINATION=\"OS=9.1,name=iPhone 5s\""
    - DESTINATION="arch=x86_64"
xcode_scheme:
  - Strutter iOS
  - Strutter Mac
  - Strutter iOS OALayout
xcode_sdk: 
  - iphonesimulator
  - macosx10.11
script: 
  - xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$DESTINATION"
matrix:
  exclude:
    -
      xcode_scheme: Strutter iOS
      xcode_sdk: macosx10.11
    -
      xcode_scheme: Strutter iOS OALayout
      xcode_sdk: macosx10.11
    - 
      xcode_scheme: Strutter Mac
      xcode_sdk: iphonesimulator9.0
    - 
      xcode_scheme: Strutter iOS
      env: "DESTINATION=\"OS=8.4,name=iPhone 5s\""
    - 
      xcode_scheme: Strutter iOS
      env: "DESTINATION=\"OS=8.4,name=iPhone 4s\""
  include:
    -
      xcode_scheme: Strutter Mac
      env: DESTINATION="arch=x86_64"