language: objective-c
osx_image: xcode7.2b1
xcode_workspace: Strutter.xcworkspace
env:
  global:
    - "IOS8_32=\"OS=8.4,name=iPhone 4s\""
    - "IOS8_64=\"OS=8.4,name=iPhone 5s\""
    - "IOS9_32=\"OS=9.0,name=iPhone 4s\""
    - "IOS9_64=\"OS=9.0,name=iPhone 5s\""
  matrix:
    - DESTINATION="$IOS8_32"
    - DESTINATION="$IOS8_64"
    - DESTINATION="$IOS9_32"
    - DESTINATION="$IOS9_64"
xcode_scheme:
  - "Strutter iOS"
  - "Strutter iOS OALayout"
xcode_sdk: iphonesimulator
  # - macosx10.11
matrix:
  exclude:
    -
      xcode_scheme: "Strutter iOS"
      env: DESTINATION="$IOS8_32"
    - 
      xcode_scheme: "Strutter iOS"
      env: DESTINATION="$IOS8_64"
  include:
    -
      xcode_scheme: "Strutter Mac"
      xcode_sdk: macosx10.11
      env: DESTINATION="arch=x86_64"
script: 
  - echo xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$DESTINATION"
  - xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$DESTINATION"
